version: "3.8"

services:
  assets:
    image: nginx:alpine
    container_name: assets_server
    expose:
      - "80"
    volumes:
      - ../api-digital-announce-system/digital-announce-system/storage/app/public:/usr/share/nginx/html/storage
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pengumuman-net


networks:
  pengumuman-net:
    external: true
  