services:
  nginx:
    image: nginx:alpine
    container_name: nginx_api
    expose:
      - "80"
    volumes:
      - ./digital-announce-system:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - pengumuman-net

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php_fpm_api
    volumes:
      - ./digital-announce-system:/var/www
    networks:
      - pengumuman-net

networks:
  pengumuman-net:
    external: true
