services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_ui
    expose:
      - "3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules  # Named volume untuk node_modules
    networks:
      - pengumuman-net
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "pengumuman.test:host-gateway"
      - "db.pengumuman.test:host-gateway"

volumes:
  node_modules:  # Persistent named volume

networks:
  pengumuman-net:
    external: true
